name: Build & Push Windows Docker Image

on:
  push:
    branches: [ "docker-development" ]
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Tag for the Docker image'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: windows-2019  
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3

      - name: Restore NuGet packages
        run: nuget restore MovieReview-Angular.sln

      - name: Build Solution
        run: msbuild MovieReview-Angular.sln /p:Configuration=Release

      - name: Publish Web App
        run: msbuild MovieReview.Web/MovieReview.Web.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:OutputPath=publish

      - name: Docker Hub Login
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Log in to Amazon ECR
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.ACCOUNT_ID }}:role/github-actions-role
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # Build Docker Image
      - name: Build Docker Image
        run: |
          docker build `
            --file Dockerfile `
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/moviereview:${{ github.event.inputs.image_tag }} `
            --tag ${{ steps.login-ecr.outputs.registry }}/moviereview:${{ github.event.inputs.image_tag }} .

      # Push to Docker Hub
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/moviereview:${{ github.event.inputs.image_tag }}

      # Push to Amazon ECR
      - name: Push to Amazon ECR
        run: docker push ${{ steps.login-ecr.outputs.registry }}/moviereview:${{ github.event.inputs.image_tag }}
